#!/bin/bash 

PATH="/sbin:/bin" 

load_firmware() { 
   local FN=/lib/firmware/"$FIRMWARE" 
   if [[ ! -e "$FN" ]]; then 
      echo "$FN not found" 
      return 1 
   fi 
   if ! cd /sys; then 
      return 1 
   fi 
   local fst=$(stat -f -c %T .) 
   if [[ "$fst" != 'sysfs' ]]; then 
      echo "mounting /sys for $FN -> $DEVPATH" 
      mount -n -t sysfs sysfs /sys || return 1 
      if ! cd /sys; then 
         umount -n -l /sys 
         return 1 
      fi 
   else 
      echo "loading $FN -> $DEVPATH" 
   fi 
   echo 1 >"./$DEVPATH/loading" 
   rc=$? 
   if [[ $rc -eq 0 ]]; then 
      cat "$FN">"./$DEVPATH/data" 
      rc=$? 
   fi 
   if [[ $rc -eq 0 ]]; then 
      echo 0 >"./$DEVPATH/loading" 
   else 
      echo -1 >"./$DEVPATH/loading" 
   fi 
   if [[ "$fst" != 'sysfs' ]]; then 
      umount -n -l . 
   fi 
   cd / 
   return $rc 
} 

if [[ "$ACTION" != 'add' ]]; then 
   exit 0 
fi 
if [[ "$FIRMWARE" == '' ]]; then 
   exit 0 
fi 

exec >/dev/console 2>&1 
if ! load_firmware; then 
   echo "failed to load $FN -> $DEVPATH" 
fi 
exit 0
