#!/bin/sh
#
# BerryBoot, ugly but functional image chooser thingy
#
# Author: Floris Bos
#

# Standard busybox init
/bin/mount -t proc proc /proc
/bin/mount -o remount,rw,noatime / 
#/bin/mount -a
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs dev /dev
/bin/hostname -F /etc/hostname

# Prevent kernel messages being printed through our menu
echo 0 > /proc/sys/kernel/printk

# Show dialog
/usr/bin/BerrybootUI 2>/tmp/answer


# Clear & re-enable kernel messages
clear
echo 1 > /proc/sys/kernel/printk

IMAGE=`cat /tmp/answer`
DATADIR="/mnt/data/$IMAGE"
rm /tmp/answer

if [ "$IMAGE" != "" ]; then
	mkdir -p /squashfs /aufs $DATADIR
	clear
	echo Mounting image ${IMAGE}...
	mount -o loop "/mnt/images/$IMAGE" /squashfs
	echo Mounting RW data directory on top
	mount -t aufs -o br:${DATADIR}:/mnt/shared:/squashfs none /aufs
	cd /aufs
#	umount /sys
#	umount /tmp
#	umount /proc
	mount -o move /dev dev
	mount -o move /sys sys
	mount -o move /proc proc
	echo Starting operating system ${IMAGE}...
	exec switch_root . /sbin/init
fi

# In case the user pressed cancel or something went wrong, show an emergency recovery shell
clear
echo
echo Emergency recovery shell activated
echo

/bin/sh
