#!/bin/sh
#
# BerryBoot, ugly but functional image chooser thingy
#
# Author: Floris Bos
#

# Standard busybox init
/bin/mount -t proc proc /proc
/bin/mount -o remount,rw,noatime / 
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs dev /dev
/bin/hostname -F /etc/hostname

if grep -q debugconsole /proc/cmdline; then
	/sbin/getty -L tty2 0 vt100 &
fi

if grep -q "mmc0_led" /proc/cmdline; then
	if [ -e /sys/class/leds/ph20:green:led1 ]; then
		echo mmc0 > /sys/class/leds/ph20:green:led1/trigger
	fi
fi

if grep -q vncinstall /proc/cmdline; then
	export QWS_DISPLAY="VNC:size=800x600:depth=32:0"
	echo
	echo Connect with your VNC client
	echo If you wish to disable VNC mode: remove 'vncinstall' from cmdline.txt
	echo
fi

# Show GUI, it will write the OS choosen to /tmp/answer
/usr/bin/BerrybootGUI -qws 2>/tmp/debug 

# Clear screen
clear

IMAGE=`cat /tmp/answer`
DATADIR="/mnt/data/$IMAGE"
SHAREDDIR="/mnt/shared"
IMAGEPATH="/mnt/images/$IMAGE"
rm /tmp/answer

#
# Set CPU governor to "ondemand" when booting an OS on the Pi
# Set it to "performance" for other devices
#
if grep -q "BCM" /proc/cpuinfo; then
	GOVERNOR=ondemand
else
	GOVERNOR=performance
fi

if [ "$IMAGE" != "" ]; then
	mkdir -p /squashfs /aufs $DATADIR
	clear

	if [ -s ${DATADIR}/storage/.update/SYSTEM ]; then
            echo "Updating OpenELEC"
            mv -f ${DATADIR}/storage/.update/SYSTEM ${IMAGEPATH}
            rm -rf ${DATADIR}/storage/.update/*
	fi

	echo Mounting image ${IMAGE}...
	mount -o loop ${IMAGEPATH} /squashfs
	cd /squashfs

	if [ -e berryboot-init ]; then
		echo Executing init script
		. berryboot-init
	fi

	if [ -L lib -o -L sbin ]; then
		echo
		echo Error: having a symlink for /lib and/or /sbin inside your image is not allowed!
		echo This conflicts with the shared AUFS folders
		echo
                sleep 5
	fi

	for initfile in sbin/init usr/lib/systemd/systemd lib/systemd/systemd init
	do
		if [ -e $initfile ]; then
			echo Mounting RW data directory on top
			mount -t aufs -o br:${DATADIR}:${SHAREDDIR}:/squashfs none /aufs
			cd /aufs
			mount -o move /dev dev
			mount -o move /sys sys
			mount -o move /proc proc
			echo Setting CPU governor to $GOVERNOR
			echo "$GOVERNOR" > sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
			echo Starting operating system ${IMAGE}...
			exec switch_root . $initfile
		fi
	done

	echo
	echo Error: unable to locate or execute /sbin/init /usr/lib/systemd/systemd /init inside $IMAGE
	echo
	sleep 5
fi

# In case the user pressed cancel or something went wrong, show an emergency recovery shell
clear
echo
echo Emergency recovery shell activated
echo

/bin/sh
